export const loveStories = [
  {
    id: 1,
    name: "Aman ❤️ Priya",
    maleImage: "https://randomuser.me/api/portraits/men/21.jpg",
    femaleImage: "https://randomuser.me/api/portraits/women/40.jpg",
    story: "Met on Crushes and found true love 🌹",
  },
  {
    id: 2,
    name: "Ravi ❤️ Simran",
    maleImage: "https://randomuser.me/api/portraits/men/27.jpg",
    femaleImage: "https://randomuser.me/api/portraits/women/22.jpg",
    story: "From chatting to forever 💍",
  },
  // {
  //   id: 3,
  //   name: "Vijay ❤️ Anjali",
  //   maleImage: "https://randomuser.me/api/portraits/men/33.jpg",
  //   femaleImage: "https://randomuser.me/api/portraits/women/35.jpg",
  //   story: "Found a beautiful connection over shared interests. 💖",
  // },
  {
    id: 4,
    name: "Kabir ❤️ Meera",
    maleImage: "https://randomuser.me/api/portraits/men/44.jpg",
    femaleImage: "https://randomuser.me/api/portraits/women/45.jpg",
    story: "Swiped right, and it changed everything! ✨",
  },
  {
    id: 5,
    name: "Sanjay ❤️ Neha",
    maleImage: "https://randomuser.me/api/portraits/men/33.jpg",
    femaleImage: "https://randomuser.me/api/portraits/women/35.jpg",
    story: "Two profiles, one destiny. Now engaged! 👰‍♀️",
  },
  {
    id: 6,
    name: "Rohit ❤️ Dia",
    maleImage: "https://randomuser.me/api/portraits/men/62.jpg",
    femaleImage: "https://randomuser.me/api/portraits/women/63.jpg",
    story: "Magical first date, thanks to Crushes. 🥂",
  },
  {
    id: 7,
    name: "Akash ❤️ Tanisha",
    maleImage: "https://randomuser.me/api/portraits/men/77.jpg",
    femaleImage: "https://randomuser.me/api/portraits/women/78.jpg",
    story: "Proving that real love still exists! 💘",
  },
  {
    id: 8,
    name: "Dev ❤️ Kiara",
    maleImage: "https://randomuser.me/api/portraits/men/85.jpg",
    femaleImage: "https://randomuser.me/api/portraits/women/86.jpg",
    story: "Matched in Mumbai, living happily ever after!",
  },
];
